config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks", to: "tasks#destroy", as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end
  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end
  def destroy
    @task = Task.find(params[:format])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <% if !f.object.new_record? %>
    <%= f.input :completed, as: :boolean, checked_value: true, unchecked_value: false %>
  <% end %>
  <%= f.submit %>
<% end %>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit <%= @task.title %></h1>

  <%= render "form", task: @task %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
      <% if task.completed %>
        <li><i class="far fa-check-square"></i><%= link_to task.title, task_path(task) %>
          <%= link_to destroy_task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash"></i>    
          <% end %></li>
      <% else %>
        <li><i class="far fa-square"></i><%= link_to task.title, task_path(task) %>
          <%= link_to destroy_task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash"></i>    
          <% end %></li>
      <% end %>
    <% end %>
  </ul>
  <%= link_to "Add a new task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New task</h1>

  <%= render "form", task: @task %>
  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
  <% if @task.completed %>
  <p><%= "This task is completed"%></p>
  <% else %>
  <p><%= "This task is not completed yet"%></p>
  <% end %>

  <%= link_to "Back to list", tasks_path %>
  <%= link_to "Edit", edit_task_path(@task) %>
</div>